{application,eini,
             [{description,"An Erlang INI parser"},
              {vsn,"1.2.6"},
              {applications,[kernel,stdlib]},
              {modules,[eini,eini_app,eini_lexer,eini_parser,eini_sup]},
              {registered,[]},
              {mod,{eini_app,[]}},
              {licenses,["Apache 2.0"]},
              {links,[{"Github","https://github.com/erlcloud/eini"}]},
              {exclude_files,["src/eini_parser.erl","src/eini_lexer.erl"]}]}.
